### ISSUE TITLE
Question: System Requirements

### ISSUE THREAD

**Issue by ghost** [PhiTux/schoco#2]
Hey, this seems to be quite an intriguing project!
I am currently thinking about using it for a 20 – 30 people class, do you have any experience about how big of a VPS I'd need for such a size?
Thanks in advance!

**Comment by PhiTux** [comment]
Hey, thank you :)
That's an important question, I need to update/add this in the Readme.

We used it once with about 45 pupils at the same time (three courses in parallel).
We use a VPS with 10 dedicated (!) cores and 32 Gigs of RAM. We bought this powerful VPS, as I also didn't really know how much power my own project would need. 
Actually this setup is overpowered for us! Even with those 45 pupils at the same time!

You have to consider, that the CPU is only used, when a pupil clicks on "compile", "execute" or "test"... And this actually happens quite rarely. So for your use case, I would guess, that a setup with 4 cores and about 8 gigs or RAM is quite fine.

I just noticed one thing: using a shared core can reduce the "snappiness" dramatically. I really recommend using a VPS with dedicated cores for your server.

Hope this helps ;-)

**Comment by ghost** [comment]
Wow, that was a fast response. That's exactly the kind of information I was looking for. Thanks a lot!
